version: "3"

services:
  chat.chronx.dev:
    container_name: chat.chronx.dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    volumes:
      - ./next-app:/app/
    restart: always
    ports:
      - "127.0.0.1:444:3000"
    networks:
      - chronx-dev-network

networks:
  chronx-dev-network:
    external: true
