version: "3"

services:
  chat.chronx.dev:
    container_name: chat.chronx.dev
    build:
      context: .
      dockerfile: prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - "127.0.0.1:81:3000"
    networks:
      - chronx-dev-network

networks:
  chronx-dev-network:
    external: true
